'use client'

import React, { useEffect, useState } from 'react'
import { motion } from 'motion/react'
import { FileText, Download, CheckCircle, Clock, PenLine } from 'lucide-react'
import { StudentDashboardLayout } from '@/components/student/layout/StudentDashboardLayout'
import { createClient } from '@/lib/supabase/client'
import type { Agreement } from '@/types/student'

const GOLD = '#C9A84C'
const fmtDate = (d: string | null) => d ? new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' }) : '—'

export default function AgreementPage() {
  const supabase = createClient()
  const [agreement, setAgreement] = useState<Agreement | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const load = async () => {
      const { data: { session } } = await supabase.auth.getSession()
      if (!session) return
      const { data: student } = await supabase.from('students').select('id').eq('user_id', session.user.id).single()
      if (!student) return
      const { data } = await supabase.from('agreements').select('*').eq('student_id', student.id).order('created_at', { ascending: false }).limit(1).single()
      setAgreement(data)
      setLoading(false)
    }
    load()
  }, [supabase])

  return (
    <StudentDashboardLayout title="Rental Agreement">
      {loading ? (
        <div className="bg-white rounded-2xl p-10 animate-pulse" style={{ border: '1px solid #EBEBF0' }}>
          <div className="h-6 bg-gray-100 rounded w-1/3 mb-4" />
          <div className="h-4 bg-gray-100 rounded w-2/3 mb-3" />
          <div className="h-4 bg-gray-100 rounded w-1/2" />
        </div>
      ) : !agreement ? (
        <div className="bg-white rounded-2xl p-12 text-center" style={{ border: '1px solid #EBEBF0' }}>
          <FileText size={44} className="mx-auto mb-4" style={{ color: '#C4C4D0' }} />
          <p className="text-base font-semibold" style={{ color: '#1A1A2E' }}>No agreement found</p>
          <p className="text-sm mt-1" style={{ color: '#8A8AA0' }}>Your rental agreement will appear here once generated by the admin.</p>
        </div>
      ) : (
        <div className="space-y-5">
          {/* Status Card */}
          <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}
            className="bg-white rounded-2xl p-6"
            style={{ border: '1px solid #EBEBF0', boxShadow: '0 2px 12px rgba(0,0,0,0.04)' }}>
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-2xl flex items-center justify-center flex-shrink-0"
                style={{ background: 'rgba(201,168,76,0.12)', border: '1px solid rgba(201,168,76,0.25)' }}>
                <FileText size={24} style={{ color: GOLD }} />
              </div>
              <div className="flex-1">
                <div className="flex items-start justify-between flex-wrap gap-2">
                  <h2 className="text-xl font-bold" style={{ fontFamily: 'var(--font-playfair), serif', color: '#1A1A2E' }}>
                    Rental Agreement
                  </h2>
                  <span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold`}
                    style={{
                      background: agreement.signed ? 'rgba(46,204,113,0.1)' : 'rgba(245,158,11,0.1)',
                      color: agreement.signed ? '#27AE60' : '#F59E0B',
                    }}>
                    {agreement.signed ? <><CheckCircle size={12} /> Signed</> : <><Clock size={12} /> Pending Signature</>}
                  </span>
                </div>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 mt-4">
                  {[
                    { label: 'Start Date', value: fmtDate(agreement.start_date) },
                    { label: 'End Date', value: fmtDate(agreement.end_date) },
                    { label: 'Signed On', value: fmtDate(agreement.signed_at || null) },
                  ].map(({ label, value }) => (
                    <div key={label}>
                      <p className="text-xs font-semibold mb-0.5" style={{ color: '#8A8AA0' }}>{label}</p>
                      <p className="text-sm font-medium" style={{ color: '#1A1A2E' }}>{value}</p>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </motion.div>

          {/* Signature Info */}
          {agreement.signed && agreement.signature_data && (
            <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}
              className="bg-white rounded-2xl p-5"
              style={{ border: '1px solid #EBEBF0' }}>
              <h3 className="text-sm font-bold mb-3" style={{ color: '#1A1A2E' }}>Digital Signature</h3>
              <div className="flex items-center gap-3 p-3 rounded-xl" style={{ background: '#F8F6F1' }}>
                <PenLine size={18} style={{ color: GOLD }} />
                <p className="text-sm font-semibold italic" style={{ color: '#1A1A2E' }}>{agreement.signature_data}</p>
              </div>
              <p className="text-xs mt-2" style={{ color: '#8A8AA0' }}>Signed on {fmtDate(agreement.signed_at || null)}</p>
            </motion.div>
          )}

          {/* Download Button */}
          {agreement.file_url && (
            <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
              <a href={agreement.file_url} target="_blank" rel="noreferrer"
                className="inline-flex items-center gap-2 px-5 py-3 rounded-xl font-semibold text-sm transition-all duration-200"
                style={{
                  background: 'linear-gradient(135deg, #C9A84C, #E8C96B)',
                  color: '#1A1A2E',
                  boxShadow: '0 4px 16px rgba(201,168,76,0.3)',
                }}>
                <Download size={17} />
                Download Agreement PDF
              </a>
            </motion.div>
          )}
        </div>
      )}
    </StudentDashboardLayout>
  )
}
